name: Build Container

on:
  workflow_dispatch:

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: tests/Containerfile-build
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/containers/hirte-build:latest
        labels: |
          org.opencontainers.image.source=https://github.com/containers/hirte
          org.opencontainers.image.description="Base container for testing hirte"
          org.opencontainers.image.licenses=GPL-2.0-only
